import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import TextInput from "@/components/TextInput";
import SubmitButton from "@/components/SubmitButton";
import GetResponse from "@/components/GetResponse";
import useApi from "@/hooks/useApi";
import { getUserPrompt } from "../prompts/promptUtils";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const { data, error, loading, fetchData } = useApi();
  const [additionalInfo, setAdditionalInfo] = useState(null);

  const handleSubmit = async (event) => {
    event.preventDefault();
    const submitValue = getUserPrompt(inputValue);
    console.log("input data: ", submitValue);
    await fetchData("/api/openai", "POST", submitValue);
  };

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
    setAdditionalInfo(null); // Clear additional content when input value changes
  };

  const handleLoadMore = async () => {
    const response = await fetch("/api/additional", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ vegetable: inputValue }),
    });

    if (!response.ok) {
      console.error("Failed to fetch additional information");
      return null;
    }

    const additionalData = await response.json();
    setAdditionalInfo(additionalData.result);
    return additionalData.result;
  };

  return (
    <>
      <Head>
        <title>Know the Vegetable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1 className={inter.className}>NextJS OpenAI to Get Vegetable Description</h1>
        <p className={inter.className}>
          Enter the name of a vegetable and it will generate a description for you.
        </p>

        <form>
          <TextInput
            value={inputValue}
            onChange={handleInputChange}
            placeholder={"Enter a vegetable"}
          />
          <SubmitButton onClick={handleSubmit} disabled={loading} />
        </form>

        <GetResponse
          data={data}
          error={error}
          loading={loading}
          onLoadMore={handleLoadMore}
          additionalInfo={additionalInfo}
        />
      </main>
    </>
  );
}
