// /pages/index.js

import React, { useState } from "react";
import Head from "next/head";
import TextInput from "@/components/TextInput";
import SubmitButton from "@/components/SubmitButton";
import ResponseDisplay from "@/components/ResponseDisplay";
import useApi from "@/hooks/useApi";
import { getUserPrompt } from "prompts/promptUtils";

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const { data, error, loading, fetchData } = useApi();

  const handleSubmit = async (event) => {
    event.preventDefault();
    const promptValue = getUserPrompt(inputValue);
    await fetchData("/api/openai", "POST", promptValue);
  };

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
  };

  return (
    <>
      <Head>
        <title>NextJS OpenAI Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>NextJS OpenAI get vegetable description</h1>
        <p>
          Enter the name of a vegetable to generate its description.
        </p>
        <form onSubmit={handleSubmit}>
          <ResponseDisplay data={data} error={error} loading={loading} />
          <TextInput
            value={inputValue}
            onChange={handleInputChange}
            placeholder="Enter a vegetable"
          />
          <SubmitButton disabled={loading}>Submit</SubmitButton>
        </form>
      </main>
    </>
  );
}
